In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV

In [2]:
data = pd.read_csv('data.csv')
data = data.dropna()
data.shape

(43805, 18)

In [3]:
X = data.drop(['day', 'user_id', 'target_14d'], axis=1)
Y = data['target_14d']

In [4]:
X.columns

Index(['month_day', 'month', 'week_day', 'days_offline', 'online_days',
       'avg_online', 'offline_days', 'avg_ofline', 'avg_submits_14d',
       'success_rate_14d', 'solved_total', 'avg_level_task',
       'max_level_task_solved', 'day_score_14', 'total_score'],
      dtype='object')

In [5]:
model_1 = RidgeClassifier()
model_1.fit(X, Y)
model_1.score(X, Y)

0.9784042917475174

In [6]:
roc_auc_score(Y, model_1.predict(X))

0.49998833411105925

In [7]:
model_1.coef_, model_1.intercept_

(array([[-2.91829847e-02, -1.53668421e-01, -1.23393257e-03,
          1.53229369e-02,  6.19170696e-04, -1.02946525e-01,
         -7.79926116e-05,  1.02946525e-01, -2.98980391e-02,
         -5.39190214e-02,  7.52138335e-03,  1.32047867e-03,
          4.73424237e-04,  1.53270259e-03, -7.22566134e-03]]),
 array([-0.86370608]))

In [8]:
model_2 = RidgeClassifierCV(cv=5)
model_2.fit(X, Y)
model_2.score(X, Y)

0.9784042917475174

In [9]:
roc_auc_score(Y, model_2.predict(X))

0.49998833411105925

In [10]:
model_2.coef_, model_2.intercept_

(array([[-3.58636430e-01, -1.16540001e+00, -1.14264636e-03,
          1.53186738e-02,  3.92779920e-03, -1.03075372e-01,
          3.22734634e-03,  1.03075372e-01, -2.99309313e-02,
         -5.39685246e-02,  7.50601520e-03,  1.31731600e-03,
          4.75400439e-04,  1.53687224e-03, -7.21024837e-03]]),
 array([-0.18685184]))

In [11]:
model_3 = LogisticRegression()
model_3.fit(X, Y)
model_3.score(X, Y)

/opt/conda/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9784271201917589

In [12]:
roc_auc_score(Y, model_3.predict(X))

0.5

In [13]:
model_3.coef_, model_3.intercept_

(array([[ 0.06534785, -0.5257531 ,  0.05685462,  0.01856204, -0.07516209,
         -0.64478201,  0.0026427 , -0.09769561, -2.47956163, -0.41700846,
         -0.20706006, -0.29862989, -0.2011549 ,  0.08495633,  0.18994795]]),
 array([-0.79502429]))

In [14]:
model_4 = LogisticRegressionCV(cv=5, random_state=42)
model_4.fit(X, Y)
model_4.score(X, Y)

/opt/conda/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/conda/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

0.9781531788608606

In [15]:
roc_auc_score(Y, model_4.predict(X))

0.49986000933271113

In [16]:
model_4.coef_, model_4.intercept_

(array([[ 0.11727582, -0.0029095 , -0.01244385,  0.03404959, -0.08546996,
         -0.27282761,  0.00177018,  0.33178668, -1.38421778, -0.01073749,
         -0.10774917, -0.28669463, -0.19122497, -0.03297915,  0.09828158]]),
 array([-2.00454093]))